pipeline {

    agent any

    environment {
        IMAGE_NAME = "registry.spring.webflux/hello-world:${env.BUILD_NUMBER}"
        REGISTRY_URL = "https://spring.webflux.me"
        REGISTRY_USERNAME = "foo"
        REGISTRY_PASSWORD = "bar"
    }

    stages {

        stage("Init") {
            steps {
                echo "Init"
                echo "******************************"
                ...
            }
        }

        stage("Mvn Install") {
            steps {
                echo "Mvn Install"
                echo "******************************"
                sh 'docker run --rm -v $(pwd):/app -v ~/.m2:/root/.m2 maven:3.6.2-jdk-11 mvn -DskipTests=true clean package -f /app/pom.xml'
            }
        }

        stage("Mvn Test") {
            steps {
                echo "Mvn Test"
                echo "******************************"
                sh 'docker run --rm -v $(pwd):/app -v ~/.m2:/root/.m2 maven:3.6.2-jdk-11 mvn test -f /app/pom.xml'
            }
        }

        ...
    }
}